//! The scalar distribution surface against correctly rounded
//! references: the standard normal CDF, its survival function, its
//! density and bracket probabilities, and the chi-squared survival,
//! regularized upper incomplete gamma and log-gamma beneath them.
//!
//! # Where the references come from
//!
//! `tests/data/normal_reference_table.rs` is generated by
//! `tools/normal_reference_table.py`, which evaluates
//! \\(\Phi(x) = \operatorname{erfc}(-x/\sqrt 2)/2\\) and
//! \\(\varphi(x) = e^{-x^2/2}/\sqrt{2\pi}\\) at 60 decimal digits with
//! mpmath and rounds each once, at the end, to the nearest double. The
//! arguments are exact doubles on both sides, so the reference is the
//! value of the function at the very argument the test passes in.
//! Regenerate from the repository root with
//!
//! ```text
//! uv run --with mpmath==1.3.0 python tools/normal_reference_table.py
//! ```
//!
//! Arbitrary precision is not a flourish here. The claim under test is
//! RELATIVE accuracy across the whole representable range, and no double
//! precision routine can witness that claim about another: at 30σ the
//! naive \\(e^{-x^2/2}\\) is itself wrong by \\(1.4\times10^{-14}\\)
//! relative, so a reference built on it would certify a tail that is
//! wrong in its first fourteen digits.
//!
//! # What is asserted
//!
//! A relative error below `RELATIVE_BOUND` at every argument whose
//! reference is a normal double, and below the subnormal spacing plus
//! that bound at the arguments beyond 37.5σ whose reference is
//! subnormal. Both the worst point and its error are printed, so a
//! regression names the argument that caused it.
//!
//! mpmath: Johansson, F. et al. (2023). mpmath, version 1.3.0.
//! <https://mpmath.org>

use hyperjet::statistics::{
    chi2_sf, ln_gamma, normal_cdf, normal_cdf_difference, normal_pdf, normal_sf,
    upper_inc_gamma_reg,
};

include!("data/normal_reference_table.rs");

/// The relative accuracy the three functions claim. The worst argument
/// anywhere is 1.7465700000009603, just under the series handover, where
/// the error is 6.3e-15 against arbitrary-precision references. The
/// grid below carries that argument, so this is the measurement, not a
/// sample that happens to miss it. The bound therefore has a factor of
/// 1.6 in hand and no more, which is thin: a platform whose `exp` is a
/// unit in the last place worse than this one's would eat a good part of
/// it. Anyone tightening the bound should lower `SERIES_SWITCH` first,
/// which is the only dial that moves the number.
const RELATIVE_BOUND: f64 = 1e-14;

/// The spacing of the subnormals, `f64::MIN_POSITIVE * f64::EPSILON`.
/// Below 1e-308 a result cannot be relatively accurate at all — there
/// are only a handful of representable values left — so the four
/// references in the gradual-underflow band are held to a count of
/// these instead.
const SUBNORMAL_SPACING: f64 = f64::MIN_POSITIVE * f64::EPSILON;

/// How many subnormal steps a subnormal reference may be off by.
///
/// Below `f64::MIN_POSITIVE` there is no relative accuracy to hold a
/// result to: the gap between neighbouring representable values is a
/// fixed `SUBNORMAL_SPACING`, which at the deepest reference in the
/// table is 1.7e-8 of the value itself. Every point in that band is
/// exact on this platform; the allowance is for a different `exp` in
/// the gradual-underflow range, and is still far tighter than any real
/// regression would be.
const SUBNORMAL_STEPS: f64 = 4.0;

/// The absolute error allowed at a reference value.
fn tolerance(reference: f64) -> f64 {
    if reference >= f64::MIN_POSITIVE {
        RELATIVE_BOUND * reference
    } else {
        RELATIVE_BOUND * reference + SUBNORMAL_STEPS * SUBNORMAL_SPACING
    }
}

/// Check one function over the whole grid, reporting the worst point in
/// each of the two regimes: a relative error where the reference is a
/// normal double, and a count of subnormal steps where it is not.
fn check<F: Fn(f64) -> f64>(name: &str, reference_of: fn(&(f64, f64, f64)) -> (f64, f64), f: F) {
    let mut worst_rel = (0.0_f64, f64::NAN, f64::NAN, f64::NAN);
    let mut worst_steps = (0.0_f64, f64::NAN);
    let mut subnormal_points = 0_usize;

    for row in &NORMAL_REFERENCES {
        let (argument, reference) = reference_of(row);
        let got = f(argument);
        let error = (got - reference).abs();
        assert!(
            error <= tolerance(reference),
            "{name}({argument}) = {got:e}, reference {reference:e}, \
             off by {error:e} against a tolerance of {:e}",
            tolerance(reference)
        );
        if reference <= 0.0 || reference >= 1.0 {
            continue;
        }
        if reference >= f64::MIN_POSITIVE {
            let rel = error / reference;
            if rel > worst_rel.0 {
                worst_rel = (rel, argument, got, reference);
            }
        } else {
            subnormal_points += 1;
            let steps = error / SUBNORMAL_SPACING;
            if steps > worst_steps.0 {
                worst_steps = (steps, argument);
            }
        }
    }

    assert!(
        subnormal_points >= 6,
        "{name}: the grid stopped reaching the subnormal range"
    );
    println!(
        "{name}: worst relative error {:e} at {} (got {:e}, reference {:e}); \
         worst subnormal point {} steps at {}",
        worst_rel.0, worst_rel.1, worst_rel.2, worst_rel.3, worst_steps.0, worst_steps.1
    );
}

/// How much a bracket cancels: the larger of the two quantities the
/// routine combines, divided by the answer. That is the factor by which
/// their own relative error reaches the result, and it is 1 for any
/// bracket that holds most of the mass on its side.
fn bracket_magnification(hi: f64, lo: f64, reference: f64) -> f64 {
    let larger = if lo > 0.0 || hi < 0.0 {
        normal_sf(lo.abs().min(hi.abs())).max(normal_cdf(-lo.abs().max(hi.abs())))
    } else {
        // The straddling arm adds two positive halves, so the only
        // magnification is that of the larger half against the sum.
        (0.5 - normal_sf(hi.abs())).max(0.5 - normal_sf(lo.abs()))
    };
    (larger / reference).max(1.0)
}

#[test]
fn the_cdf_matches_correctly_rounded_references() {
    check("Phi", |row| (row.0, row.1), normal_cdf);
}

/// `Q(x) = Phi(-x)` exactly, so the survival function is checked against
/// the mirrored row of the same table.
#[test]
fn the_survival_function_matches_correctly_rounded_references() {
    check("Q", |row| (-row.0, row.1), normal_sf);
}

#[test]
fn the_density_matches_correctly_rounded_references() {
    check("phi", |row| (row.0, row.2), normal_pdf);
}

/// The table has to be what the test assumes it is: symmetric about the
/// origin, ascending, and carrying the arguments the accuracy claim is
/// quoted at. A generator that silently emitted half a grid would
/// otherwise leave every assertion above still passing.
#[test]
fn the_reference_grid_is_the_one_the_claim_is_quoted_over() {
    assert!(NORMAL_REFERENCES.len() > 200);

    for pair in NORMAL_REFERENCES.windows(2) {
        assert!(
            pair[1].0 > pair[0].0,
            "the grid is not ascending at {}",
            pair[0].0
        );
    }

    let arguments: Vec<f64> = NORMAL_REFERENCES.iter().map(|row| row.0).collect();
    for &anchor in &[
        0.0_f64, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0, 15.0, 20.0, 30.0, 37.0,
    ] {
        assert!(
            arguments.contains(&anchor) && arguments.contains(&-anchor),
            "the grid is missing ±{anchor}"
        );
    }

    // Symmetric in the argument, and the densities mirror exactly.
    let last = NORMAL_REFERENCES.len() - 1;
    for (i, row) in NORMAL_REFERENCES.iter().enumerate() {
        let mirror = NORMAL_REFERENCES[last - i];
        assert_eq!(row.0, -mirror.0);
        assert_eq!(row.2, mirror.2);
    }

    // The deepest reference is subnormal, which is what makes the
    // subnormal arm of `tolerance` reachable rather than decorative.
    assert!(NORMAL_REFERENCES[0].1 > 0.0);
    assert!(NORMAL_REFERENCES[0].1 < f64::MIN_POSITIVE);
}

/// A tolerance no measurement can fail proves nothing. Perturb the
/// function under test by twice the bound and require the comparison to
/// notice, at a point in the deep tail and at a point in the bulk.
#[test]
fn the_comparison_would_catch_an_error_at_the_bound() {
    for &x in &[-0.5_f64, -6.0, -30.0] {
        let reference = NORMAL_REFERENCES
            .iter()
            .find(|row| row.0 == x)
            .expect("the grid carries this argument")
            .1;
        let nudged = reference * (1.0 + 2.0 * RELATIVE_BOUND);
        assert!(
            (nudged - reference).abs() > tolerance(reference),
            "a {:e} relative error at {x} would slip through",
            2.0 * RELATIVE_BOUND
        );
        // And the real value does not.
        assert!((normal_cdf(x) - reference).abs() <= tolerance(reference));
    }
}

/// The single argument at which the whole function is least accurate,
/// named so that it cannot quietly leave the grid. It sits in the gap
/// the eighth-spaced grid used to leave between 1.625 and 1.75, which is
/// why an earlier version of this suite reported a worst case a factor
/// of 1.7 too good.
#[test]
fn the_worst_argument_is_on_the_grid_and_is_still_the_worst() {
    const WORST: f64 = 1.7465700000009603;
    const REFERENCE: f64 = 0.040355977427686124;

    let row = NORMAL_REFERENCES
        .iter()
        .find(|row| row.0 == -WORST)
        .expect("the grid must carry the function's worst argument");
    assert_eq!(row.1, REFERENCE);

    let error = (normal_cdf(-WORST) - REFERENCE).abs() / REFERENCE;
    assert!(
        error < RELATIVE_BOUND,
        "the worst argument is off by {error:e}"
    );
    assert!(
        error > 0.5 * RELATIVE_BOUND,
        "the worst argument is now only off by {error:e}; if that is a real \
         improvement, re-measure and lower the bound rather than leaving \
         headroom nobody has checked"
    );
    assert_eq!(normal_sf(WORST), normal_cdf(-WORST));
}

/// `normal_cdf_difference` against correctly rounded brackets.
///
/// The last four brackets are narrow and deep in one tail, where the two
/// tails genuinely cancel; they are held to a looser bound that is
/// derived from how much they cancel rather than assumed, so the test
/// says what the routine does and does not rescue.
#[test]
fn the_bracket_probability_matches_correctly_rounded_references() {
    let mut worst = (0.0_f64, 0.0_f64, 0.0_f64);
    for &(hi, lo, reference) in &NORMAL_DIFFERENCE_REFERENCES {
        let got = normal_cdf_difference(hi, lo);

        let magnification = bracket_magnification(hi, lo, reference);
        let allowed = RELATIVE_BOUND * magnification;

        let error = (got - reference).abs() / reference;
        assert!(
            error <= allowed,
            "Phi({hi}) - Phi({lo}) = {got:e}, reference {reference:e}, \
             off by {error:e} against {allowed:e} at a magnification of {magnification:e}"
        );
        if error > worst.0 {
            worst = (error, hi, lo);
        }

        // Either order, and the sign follows the order.
        assert_eq!(normal_cdf_difference(lo, hi), -got);
    }
    println!(
        "worst bracket relative error {:e} at ({}, {})",
        worst.0, worst.1, worst.2
    );
}

/// The claim the bracket function exists to make, and its limit.
///
/// Where a bracket holds a decent share of the tail beside it, the naive
/// difference of CDF values loses figures that this keeps, by orders.
/// Where the bracket is so narrow that its OWN cancellation dominates,
/// both forms are differencing nearly equal numbers and neither is
/// guaranteed better — which of them lands closer is the luck of the
/// rounding. The split between the two regimes is the magnification, so
/// that is what selects here rather than a hand-drawn list.
#[test]
fn the_bracket_probability_beats_a_naive_difference_where_it_can() {
    for &(hi, lo, reference) in &NORMAL_DIFFERENCE_REFERENCES {
        if hi > 0.0 && lo < 0.0 {
            continue; // straddling: the naive form is fine there.
        }
        let naive = normal_cdf(hi) - normal_cdf(lo);
        let good = normal_cdf_difference(hi, lo);
        let naive_error = (naive - reference).abs() / reference;
        let good_error = (good - reference).abs() / reference;
        let magnification = bracket_magnification(hi, lo, reference);

        if magnification < 100.0 {
            assert!(
                good_error <= naive_error,
                "the bracket form is worse at ({hi}, {lo}): \
                 {good_error:e} against {naive_error:e}, magnification {magnification:e}"
            );
        } else {
            // Both are ruined by the width; only the shared allowance
            // applies, and the point of the row is to record that.
            assert!(
                good_error <= RELATIVE_BOUND * magnification,
                "({hi}, {lo}) exceeds even its magnified allowance: {good_error:e}"
            );
        }
        println!(
            "({hi}, {lo}): naive {naive_error:e}, bracket {good_error:e}, \
             magnification {magnification:e}"
        );
    }
}

/// A bracket with an endpoint exactly at the origin is the case a
/// same-side arm ruins: the tail there is exactly one half, and
/// subtracting it from the tail beside it keeps nothing of a narrow
/// bracket. Both signed zeros are exercised, since the arm is selected
/// by a comparison that treats them alike and the negation inside it
/// does not.
#[test]
fn a_bracket_with_an_endpoint_at_the_origin_keeps_its_figures() {
    // Read from the generated table rather than transcribed, so the
    // reference cannot drift from the one the rest of the suite uses.
    let cases: Vec<(f64, f64, f64)> = NORMAL_DIFFERENCE_REFERENCES
        .iter()
        .copied()
        .filter(|&(hi, lo, _)| hi == 0.0 || lo == 0.0)
        .collect();
    assert!(
        cases.len() >= 6,
        "the grid stopped carrying brackets that touch the origin"
    );
    for (hi, lo, reference) in cases {
        let error = (normal_cdf_difference(hi, lo) - reference).abs() / reference;
        assert!(
            error < RELATIVE_BOUND,
            "Phi({hi}) - Phi({lo}) is off by {error:e}"
        );
        // A width of 1e-9 is where a same-side arm would be wrong by
        // about 3e-8, so this bound is eight orders from passing by luck.
        assert_eq!(
            normal_cdf_difference(lo, hi),
            -normal_cdf_difference(hi, lo)
        );
    }

    // Signed zeros, on both ends and in every combination.
    for &(hi, lo) in &[(0.0_f64, -0.0_f64), (-0.0, -0.0), (0.0, 0.0), (-0.0, 0.0)] {
        assert_eq!(
            normal_cdf_difference(hi, lo).abs(),
            0.0,
            "a bracket of zero width should be zero, got {}",
            normal_cdf_difference(hi, lo)
        );
    }
    for &zero in &[0.0_f64, -0.0] {
        assert_eq!(
            normal_cdf_difference(1.0, zero),
            normal_cdf_difference(1.0, 0.0)
        );
        assert_eq!(
            normal_cdf_difference(zero, -1.0),
            normal_cdf_difference(0.0, -1.0)
        );
        // Half the mass sits on each side of the origin.
        assert_eq!(normal_cdf_difference(f64::INFINITY, zero), 0.5);
    }
}

/// What the incomplete gamma may be off by at a given `(a, x)`.
///
/// Its error is set by the largest intermediate in the exponent
/// `-x + a ln x - lnΓ(a)` rather than by the answer, so it grows with
/// the arguments and not with the result. Below `a = 100` the flat bound
/// dominates and this is that bound; above it the mechanism does, which
/// is why a single constant cannot describe the whole domain and why
/// the documentation states both.
fn allowance(flat: f64, a: f64, x: f64) -> f64 {
    let mechanism = 4.0 * f64::EPSILON * x.max(a * x.ln().abs());
    flat.max(mechanism)
}

/// The chi-squared survival function.
///
/// The values this replaces were transcribed rather than computed, and
/// three of the six were wrong — one in its fifth significant figure —
/// under a tolerance of 1e-4 that could not have noticed. That tolerance
/// would have passed a routine degraded from 1e-15 to 1e-5, which is to
/// say destroyed, on a function with sixteen call sites in the engine.
#[test]
fn the_chi_squared_survival_matches_correctly_rounded_references() {
    const BOUND: f64 = 5e-13;
    let mut worst = (0.0_f64, 0.0_f64, 0_usize);
    let mut documented = (0.0_f64, 0.0_f64, 0_usize);
    for &(x, k, reference) in &CHI2_SF_REFERENCES {
        let got = chi2_sf(x, k);
        if reference == 0.0 {
            // Deep enough in the tail that the true value is under the
            // smallest double. There is no relative error to take.
            assert_eq!(
                got, 0.0,
                "chi2_sf({x}, {k}) = {got:e} where the true value is 0"
            );
            continue;
        }
        let error = (got - reference).abs() / reference;
        assert!(
            error < allowance(BOUND, k as f64 / 2.0, x / 2.0),
            "chi2_sf({x}, {k}) = {got:e}, reference {reference:e}, off by {error:e}"
        );
        if error > worst.0 {
            worst = (error, x, k);
        }
        if k <= 15 && x <= 2000.0 && error > documented.0 {
            documented = (error, x, k);
        }
    }
    println!(
        "chi2_sf: worst relative error {:e} at (x = {}, k = {}); \
         worst inside the documented k <= 15, x <= 2000 is {:e} at (x = {}, k = {})",
        worst.0, worst.1, worst.2, documented.0, documented.1, documented.2
    );
    // The documented range carries its own bound and its own witness,
    // rather than borrowing the mechanism allowance that the large-k
    // rows need.
    assert!(
        documented.0 < BOUND,
        "inside k <= 15 and x <= 2000 the worst is {:e}, over the documented {BOUND:e}",
        documented.0
    );
    // The bound has to be able to fail, or it is decoration. The worst
    // measured here is 1.6e-14, at the largest x and k on the grid, so
    // the bound has about a factor of six in hand — room for another
    // platform's `exp` and `ln`, and six orders tighter than the 1e-4 it
    // replaces, which would have passed a routine degraded to 1e-5.
    assert!(
        worst.0 > 0.0,
        "every reference matched to the bit; suspect the harness"
    );
}

/// The regularized upper incomplete gamma, on both sides of its internal
/// seam at `x = a + 1`.
#[test]
fn the_upper_incomplete_gamma_matches_correctly_rounded_references() {
    const BOUND: f64 = 1e-12;
    let mut worst = (0.0_f64, 0.0_f64, 0.0_f64);
    for &(a, x, reference) in &UPPER_INC_GAMMA_REFERENCES {
        let got = upper_inc_gamma_reg(a, x);
        if reference == 0.0 {
            assert_eq!(got, 0.0, "Q({a}, {x}) = {got:e} where the true value is 0");
            continue;
        }
        let error = (got - reference).abs() / reference;
        assert!(
            error < allowance(BOUND, a, x),
            "Q({a}, {x}) = {got:e}, reference {reference:e}, off by {error:e}"
        );
        if error > worst.0 {
            worst = (error, a, x);
        }
    }
    println!(
        "upper_inc_gamma_reg: worst relative error {:e} at (a = {}, x = {})",
        worst.0, worst.1, worst.2
    );
}

/// Log-gamma, including the small arguments that used to return
/// infinity and the two zeros where a relative claim cannot hold.
#[test]
fn the_log_gamma_matches_correctly_rounded_references() {
    // The zeros of ln Gamma, at x = 1 and x = 2. Beside them the
    // function passes through nothing while the absolute error stays
    // near 1e-15, so a relative bound is the wrong instrument there and
    // an absolute one is the right one. Both are asserted, each where it
    // means something, and the exception is pinned below rather than
    // waved at.
    const NEAR_A_ZERO: f64 = 1e-2;
    const RELATIVE: f64 = 1e-14;
    const ABSOLUTE: f64 = 1e-14;

    let mut worst_relative = (0.0_f64, 0.0_f64);
    for &(x, reference) in &LN_GAMMA_REFERENCES {
        let got = ln_gamma(x);
        assert!(got.is_finite(), "ln Γ({x}) = {got}");
        if reference.abs() > NEAR_A_ZERO {
            // Away from the zeros the relative claim is the real one.
            // An absolute bound would be meaningless here: ln Γ runs to
            // 2.2e11 at the top of this grid, where 1e-14 of it is
            // 2.2e-3.
            let error = (got - reference).abs() / reference.abs();
            assert!(
                error < RELATIVE,
                "ln Γ({x}) = {got:e}, reference {reference:e}, off by {error:e}"
            );
            if error > worst_relative.0 {
                worst_relative = (error, x);
            }
        } else {
            // Beside a zero the function passes through nothing and only
            // the absolute error means anything.
            assert!(
                (got - reference).abs() < ABSOLUTE,
                "ln Γ({x}) = {got:e}, reference {reference:e}"
            );
        }
    }
    println!(
        "ln_gamma: worst relative error {:e} at x = {} (away from the zeros)",
        worst_relative.0, worst_relative.1
    );

    // The exception itself, pinned. These two arguments are where the
    // relative error is largest: 1.7e-12 and 1.0e-12, a hundred times
    // the relative bound above, while the absolute error at both is
    // about 1e-15 — which is the whole point, since a caller that
    // exponentiates this, as `upper_inc_gamma_reg` does, feels the
    // absolute error and not the relative one.
    for &x in &[1.000_678_084_215_155_3_f64, 1.997_680_536_308_456] {
        let reference = LN_GAMMA_REFERENCES
            .iter()
            .find(|row| row.0 == x)
            .expect("the grid carries the neighbourhoods of both zeros")
            .1;
        let got = ln_gamma(x);
        let relative = (got - reference).abs() / reference.abs();
        assert!(
            relative > 10.0 * RELATIVE,
            "ln Γ({x}) is now relatively accurate to {relative:e}; if that is real, \
             the documented exception beside the zeros should be re-measured"
        );
        assert!(
            (got - reference).abs() < ABSOLUTE,
            "ln Γ({x}) = {got:e} is off by more than an absolute {ABSOLUTE:e}"
        );
        println!(
            "beside a zero, x = {x}: relative {relative:e}, absolute {:e}",
            (got - reference).abs()
        );
    }
    // At the zeros themselves the value is an absolute rounding, not a
    // relative anything.
    assert!(ln_gamma(1.0).abs() < 1e-15);
    assert!(ln_gamma(2.0).abs() < 1e-15);
}
